### ISSUE TITLE
[Meta] To-Do

### ISSUE THREAD

**Issue by wolfy1339** [wolfy1339/TPT-NodeJS#10]
Here we will list what needs to be done, what is done, and what we want done to make this a very good TPT server.
# BMNNet To-Do List
## Miscellaneous Imporovements/Fixes
- [x] Fix ERC system
- [ ] Switch to a central MongoDB database (Ongoing in mongodb branch)
- [ ] Use higher security, something better than MD5 (maybe SHA-512 or even SHAKE256 of the current configuration or switch to SHAKE256 + MD6)
  - [ ] Client
  - [ ] Server
- [ ] Switch from Jade to something else equivalent to Jekyll? ([Wintersmith](http://wintersmith.io/) with the [wintersmith-liquid plugin](https://bitbucket.org/xorcode/wintersmith-liquid) looks like a possible option)
## Web Interface
- [ ] Profile editor
  - [ ] Profile picture changer
- [ ] Use SSL ([As described here](http://stackoverflow.com/questions/11744975/enabling-https-on-express-js))?
  - [ ] Get an SSL certificate
  - [ ] Get a domain
## Saves
- [ ] Deleting
- [ ] Voting
  - [ ] Up Votes
  - [ ] Down Votes
- [ ] Un-publishing
- [ ] Favourites
- [ ] Tags
  - [ ] Adding
  - [ ] Removing
- [x] Comments (@FeynmanTech)
## User Info/Profile</h1>
- [x] ID
- [ ] Age
- [ ] Location
- [ ] Website
- [x] Biography
- [ ] Reputation
- [ ] Save count
- [ ] Score
  - [ ] Average
  - [ ] Highest
  - [ ] Lowest

Feel free to edit the comment and add new to-do's
